# ci.yaml
tasks:
    - name: Graph metrics
      conda_env: pyspark
      cmd: spark-submit --driver-cores 18 --driver-memory 24g --num-executors 24 --master local[*] --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11 production_code_in/graph_metrics.py 
      tags: graph_metrics_production

    - name: Plot network metrics
      conda_env: graph_env 
      cmd: source activate graph_env && python production_code_in/plot_network_stats.py
      tags: network_stats
    
    - name: Download tweets 
      conda_env: rqenv
      cmd: current_dir=$PWD && source activate rqenv && cd /home/vt/RQ/ && python $current_dir/rq_downloader/job_submission.py --file $current_dir/rq_downloader/input_userids.in --output /home/vt/extra_storage/twitter_data --function download_tweets 
      tags: download_tweets_user
